### ISSUE TITLE
[Feature Request] Automatic script to setup Go workspace and FLAGs

### ISSUE THREAD

**Issue by rodneyrod** [codedust/WebTox#2]
The process of getting this up and running is quite tedious, and all changes are lost if you don't remember to persist your changes, it would be better if there was some sort of bash script which did this for the user / admin.

**Comment by codedust** [comment]
I have now added some instructions to setup the environment in README.md.
The default user is generated when you start WebTox for the first time.

What do you mean with "all changes are lost if you don't remember to persist your changes"?

**Comment by rodneyrod** [comment]
Never mind, this is perfect, thanks for the instructions.
